
modules_files = [
	'module_away.cc',
    'module_keypress.cc',
    'module_rot13.cc',
    'module_linehandler.cc',
    'module_connect.cc',
    'module_window.cc',
    'module_dcset.cc',
    'module_search.cc',
	'module_share.cc',
	'module_suggest.cc',
	'module_motd.cc',
	'module_cdmdebug.cc',
]

Import('env')

modules_objects = env.Object(modules_files)

Return('modules_objects')

